import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'introduction', // Link to introduction.mdx
    'glossary', // Link to glossary.mdx
    'references', // Link to references.mdx
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-the-robotic-nervous-system-ros-2-weeks-3-5',
        },
        {
          type: 'autogenerated',
          dirName: 'module-2-the-digital-twin-gazebo-unity-weeks-6-7',
        },
        {
          type: 'autogenerated',
          dirName: 'module-3-the-ai-robot-brain-nvidia-isaac-weeks-8-10',
        },
        {
          type: 'autogenerated',
          dirName: 'module-4-vision-language-action-weeks-11-13',
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
